import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { getAllPosts } from "../lib/post-fetcher";
import styles from "../styles/Home.module.css";
import { ModifiedPost } from "../types/post";

export interface HomePageProps {
  posts: ModifiedPost[];
}

const Home: NextPage<HomePageProps> = ({ posts }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {posts.map((post) => (
          <div key={post.id}>
            <Link href={`/${post.slug}`}>{post.title}</Link>
          </div>
        ))}
      </main>

      <footer className={styles.footer}>footer</footer>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps<HomePageProps> = async () => {
  return {
    props: {
      posts: await getAllPosts(),
    },
  };
};
